//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResistorColorCode.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResistorColorCode.App.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistor Color Code.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Band.
        /// </summary>
        internal static string FifthBand {
            get {
                return ResourceManager.GetString("FifthBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Bands.
        /// </summary>
        internal static string FiveBandResistorType {
            get {
                return ResourceManager.GetString("FiveBandResistorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Bands.
        /// </summary>
        internal static string FourBandResistorType {
            get {
                return ResourceManager.GetString("FourBandResistorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Band.
        /// </summary>
        internal static string FourthBand {
            get {
                return ResourceManager.GetString("FourthBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistor Calculator.
        /// </summary>
        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the resistor model based on number of bands.
        /// </summary>
        internal static string HomeHeaderDescription {
            get {
                return ResourceManager.GetString("HomeHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You read resistor bands beginning with the end that has the most bands..
        /// </summary>
        internal static string ResistorBandReading {
            get {
                return ResourceManager.GetString("ResistorBandReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Band.
        /// </summary>
        internal static string ResistorFirstBand {
            get {
                return ResourceManager.GetString("ResistorFirstBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth band.
        /// </summary>
        internal static string ResistorFourthBand {
            get {
                return ResourceManager.GetString("ResistorFourthBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the colors of the resistor bands..
        /// </summary>
        internal static string ResistorHeaderDescription {
            get {
                return ResourceManager.GetString("ResistorHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        internal static string ResistorMultiplierBand {
            get {
                return ResourceManager.GetString("ResistorMultiplierBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM (6th Band).
        /// </summary>
        internal static string ResistorPPMBand {
            get {
                return ResourceManager.GetString("ResistorPPMBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Band.
        /// </summary>
        internal static string ResistorSecondBand {
            get {
                return ResourceManager.GetString("ResistorSecondBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Band.
        /// </summary>
        internal static string ResistorThirdBand {
            get {
                return ResourceManager.GetString("ResistorThirdBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        internal static string ResistorToleranceBand {
            get {
                return ResourceManager.GetString("ResistorToleranceBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Bands.
        /// </summary>
        internal static string SixBandResistorType {
            get {
                return ResourceManager.GetString("SixBandResistorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Band.
        /// </summary>
        internal static string ThirdBand {
            get {
                return ResourceManager.GetString("ThirdBand", resourceCulture);
            }
        }
    }
}
